# Generated by Django 3.0.6 on 2023-08-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bod', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='nax',
        ),
        migrations.RemoveField(
            model_name='word',
            name='nuo',
        ),
        migrations.RemoveField(
            model_name='word',
            name='pam',
        ),
        migrations.RemoveField(
            model_name='word',
            name='rme',
        ),
    ]
