# Generated by Django 3.0.6 on 2023-08-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bod', '0002_auto_20230817_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='transliteration',
            field=models.CharField(default='...', max_length=40),
        ),
    ]
