# Generated by Django 3.0.6 on 2023-08-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bod', '0004_auto_20230819_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': '藏文詞條', 'verbose_name_plural': '藏文詞條'},
        ),
        migrations.AlterField(
            model_name='word',
            name='bod',
            field=models.TextField(verbose_name='藏文'),
        ),
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(choices=[('名詞', '名詞'), ('代詞', '代詞'), ('動詞', '動詞'), ('形容詞', '形容詞'), ('副詞', '副詞'), ('連詞', '連詞'), ('助詞', '助詞'), ('後綴', '後綴'), ('小品詞', '小品詞'), ('語氣詞', '語氣詞'), ('片語', '片語')], max_length=20, verbose_name='品詞'),
        ),
        migrations.AlterField(
            model_name='word',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='釋義'),
        ),
        migrations.AlterField(
            model_name='word',
            name='han',
            field=models.TextField(verbose_name='漢語'),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronunciation',
            field=models.CharField(max_length=40, verbose_name='實際發音'),
        ),
        migrations.AlterField(
            model_name='word',
            name='transliteration',
            field=models.CharField(max_length=40, verbose_name='轉寫'),
        ),
    ]
