# Generated by Django 3.0.6 on 2023-09-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bod', '0007_auto_20230912_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(choices=[('1', '名詞'), ('代詞', '代詞'), ('動詞', '動詞'), ('形容詞', '形容詞'), ('副詞', '副詞'), ('連詞', '連詞'), ('助詞', '助詞'), ('後綴', '後綴'), ('小品詞', '小品詞'), ('語氣詞', '語氣詞'), ('片語', '片語'), ('例文例句', '例文例句')], max_length=20, verbose_name='品詞'),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronunciation',
            field=models.CharField(max_length=50, verbose_name='實際發音'),
        ),
        migrations.AlterField(
            model_name='word',
            name='transliteration',
            field=models.CharField(max_length=50, verbose_name='轉寫'),
        ),
    ]
