# Generated by Django 3.1 on 2023-09-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bod', '0010_auto_20230915_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, '名詞'), (2, '代詞'), (3, '動詞'), (4, '形容詞'), (5, '副詞'), (6, '連詞'), (7, '助詞'), (8, '後綴'), (9, '小品詞'), (10, '語氣詞'), (11, '片語'), (12, '例句')], verbose_name='品詞'),
        ),
    ]
